name: Node.js CI & Docker Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    # Use the 'git-test' self-hosted runner   thing are added
    runs-on: [self-hosted, git-test]

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run build
      run: npm run build --if-present

    - name: Run tests
      run: npm test

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t vaishnavi681/my-node-app:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker push vaishnavi681/my-node-app:latest

    - name: Pull Docker image and run container
      run: |
        docker pull vaishnavi681/my-node-app:latest
        docker run -d -p 3000:3000 vaishnavi681/my-node-app:latest
